apiVersion: gateway.kyma-project.io/v2
kind: APIRule
# -----------------
metadata:
  namespace: default
  name: ea-appreciate-api
  labels:
    app.kubernetes.io/name: ea-appreciate-api
spec:
  service:
    name: ea-appreciate-svc
    port: 8100
  hosts: 
    - ea-appreciate.c-5a930ed.kyma.ondemand.com
  timeout: 900
  corsPolicy:
    exposeHeaders:
      - Content-Type
      - Transfer-Encoding
      - Keep-Alive
      - X-Frame-Options
  rules:
    - path: /*
      methods:
        - GET
        - POST
        - DELETE
        - PUT
        - OPTIONS
      noAuth: true
  gateway: kyma-system/kyma-gateway